/** Default profile field toggles (PHP field_settings parity) */
export const DEFAULT_FIELD_SETTINGS = {
  id: 1,
  religion: 'Yes',
  caste: 'Yes',
  subcaste: 'Yes',
  mother_tongue: 'Yes',
  education: 'Yes',
  occupation: 'Yes',
  income: 'Yes',
  height: 'Yes',
  weight: 'Yes',
  diet: 'Yes',
  complexion: 'Yes',
  body_type: 'Yes',
  manglik: 'Yes',
  star: 'Yes',
  moonsign: 'Yes',
  birthplace: 'Yes',
  birthtime: 'Yes',
  family_type: 'Yes',
  family_status: 'Yes',
  family_value: 'Yes',
  father_name: 'Yes',
  mother_name: 'Yes',
  about_me: 'Yes',
  partner_expectation: 'Yes',
  horoscope: 'Yes',
  aadhaar: 'Yes',
  photo: 'Yes',
  address: 'Yes',
  country: 'Yes',
  state: 'Yes',
  city: 'Yes',
  marital_status: 'Yes',
  children: 'Yes',
  smoke: 'Yes',
  drink: 'Yes',
  hobby: 'Yes',
  language_known: 'Yes',
}

/** Default SMTP / mail settings */
export const DEFAULT_EMAIL_SETTINGS = {
  id: 1,
  smtp_host: '',
  smtp_port: '587',
  smtp_secure: 'tls',
  smtp_user: '',
  smtp_pass: '',
  from_email: '',
  from_name: 'Melathalam Matrimony',
  reply_to: '',
  mail_enabled: 'No',
}
